model:
  prediction_model:
    pretrained_model_name_or_path: stabilityai/stable-unet-2-1
    input_perturbation: 0.0
    revision: null
    resolution: 512
    use_ema: false
    noise_offset: 0.0
    prediction_type: v_prediction
    max_scheduler_steps: null
    unet_down_blocks:
      - CrossAttnDownBlock2DHalfGated
      - CrossAttnDownBlock2DHalfGated
      - CrossAttnDownBlock2DHalfGated
      - DownBlock2DHalfGated

    unet_mid_block: UNetMidBlock2DCrossAttnWidthGated

    unet_up_blocks:
      - UpBlock2DHalfGated
      - CrossAttnUpBlock2DHalfGated
      - CrossAttnUpBlock2DHalfGated
      - CrossAttnUpBlock2DHalfGated

    gated_ff: true
    ff_gate_width: 32

data:
  dataset_name: coco
  data_files: null
  dataset_config_name: null
  data_dir: "/path/to/dataset"
  max_train_samples: null
  max_validation_samples: null
  year: 2017

  image_column: "image"
  caption_column: "caption"
  prompts: null
  dataloader:
    dataloader_num_workers: 0
    image_generation_batch_size: 1

training:
  local_rank: -1
  num_inference_steps: 50
  allow_tf32: false
  enable_xformers_memory_efficient_attention: false

